openapi: 3.0.0

info:
  title: Student/Room API
  version: 1.0.0

tags:
  - name: Students
    description: operations for students
  - name: Rooms
    description: operations for rooms

paths:
  /students/{id}:
    $ref: './paths/student/byID.yaml'

  /students/{id}/move:
    $ref: './paths/student/move.yaml'

  /students/add:
    $ref: './paths/student/create.yaml'

  /rooms/{id}:
    $ref: './paths/room/byID.yaml'

  /rooms/add:
    $ref: './paths/room/create.yaml'

  /rooms/{id}/students:
    $ref: './paths/room/allStudents.yaml'
